
package com.cybersource.schemas.transaction_data.transactionprocessor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import com.cybersource.schemas.transaction_data_1.ObjectFactory;
import com.cybersource.schemas.transaction_data_1.ReplyMessage;
import com.cybersource.schemas.transaction_data_1.RequestMessage;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ITransactionProcessor",
            targetNamespace = "urn:schemas-cybersource-com:transaction-data:TransactionProcessor")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface ITransactionProcessor {


    /**
     *
     * @param input
     * @return
     *     returns com.cybersource.schemas.transaction_data_1.ReplyMessage
     */
    @WebMethod(action = "runTransaction")
    @WebResult(name = "replyMessage", targetNamespace = "urn:schemas-cybersource-com:transaction-data-1.137",
               partName = "result")
    public ReplyMessage runTransaction(@WebParam(name = "requestMessage",
                                                 targetNamespace = "urn:schemas-cybersource-com:transaction-data-1.137",
                                                 partName = "input") RequestMessage input);

}
