package model;

import java.math.BigInteger;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 17 08:13:31 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustomerViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Setid,
        CustId,
        Name1,
        Descr,
        Country,
        Address1,
        Address2,
        City,
        Num1,
        State,
        Postal,
        AddressSeqNum,
        PaymentProfileViewObject,
        OpenItems,
        LovMonths1,
        LovCountries1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SETID = AttributesEnum.Setid.index();
    public static final int CUSTID = AttributesEnum.CustId.index();
    public static final int NAME1 = AttributesEnum.Name1.index();
    public static final int DESCR = AttributesEnum.Descr.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int ADDRESS1 = AttributesEnum.Address1.index();
    public static final int ADDRESS2 = AttributesEnum.Address2.index();
    public static final int CITY = AttributesEnum.City.index();
    public static final int NUM1 = AttributesEnum.Num1.index();
    public static final int STATE = AttributesEnum.State.index();
    public static final int POSTAL = AttributesEnum.Postal.index();
    public static final int ADDRESSSEQNUM = AttributesEnum.AddressSeqNum.index();
    public static final int PAYMENTPROFILEVIEWOBJECT = AttributesEnum.PaymentProfileViewObject.index();
    public static final int OPENITEMS = AttributesEnum.OpenItems.index();
    public static final int LOVMONTHS1 = AttributesEnum.LovMonths1.index();
    public static final int LOVCOUNTRIES1 = AttributesEnum.LovCountries1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustomerViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Setid.
     * @return the Setid
     */
    public String getSetid() {
        return (String) getAttributeInternal(SETID);
    }

    /**
     * Gets the attribute value for the calculated attribute CustId.
     * @return the CustId
     */
    public String getCustId() {
        return (String) getAttributeInternal(CUSTID);
    }

    /**
     * Gets the attribute value for the calculated attribute Name1.
     * @return the Name1
     */
    public String getName1() {
        return (String) getAttributeInternal(NAME1);
    }

    /**
     * Gets the attribute value for the calculated attribute Descr.
     * @return the Descr
     */
    public String getDescr() {
        return (String) getAttributeInternal(DESCR);
    }

    /**
     * Gets the attribute value for the calculated attribute Country.
     * @return the Country
     */
    public String getCountry() {
        return (String) getAttributeInternal(COUNTRY);
    }

    /**
     * Gets the attribute value for the calculated attribute Address1.
     * @return the Address1
     */
    public String getAddress1() {
        return (String) getAttributeInternal(ADDRESS1);
    }

    /**
     * Gets the attribute value for the calculated attribute Address2.
     * @return the Address2
     */
    public String getAddress2() {
        return (String) getAttributeInternal(ADDRESS2);
    }

    /**
     * Gets the attribute value for the calculated attribute City.
     * @return the City
     */
    public String getCity() {
        return (String) getAttributeInternal(CITY);
    }

    /**
     * Gets the attribute value for the calculated attribute Num1.
     * @return the Num1
     */
    public String getNum1() {
        return (String) getAttributeInternal(NUM1);
    }


    /**
     * Gets the attribute value for the calculated attribute State.
     * @return the State
     */
    public String getState() {
        return (String) getAttributeInternal(STATE);
    }

    /**
     * Gets the attribute value for the calculated attribute Postal.
     * @return the Postal
     */
    public String getPostal() {
        return (String) getAttributeInternal(POSTAL);
    }

    /**
     * Gets the attribute value for the calculated attribute AddressSeqNum.
     * @return the AddressSeqNum
     */
    public BigInteger getAddressSeqNum() {
        return (BigInteger) getAttributeInternal(ADDRESSSEQNUM);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PaymentProfileViewObject.
     */
    public RowIterator getPaymentProfileViewObject() {
        return (RowIterator) getAttributeInternal(PAYMENTPROFILEVIEWOBJECT);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OpenItems.
     */
    public RowIterator getOpenItems() {
        return (RowIterator) getAttributeInternal(OPENITEMS);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovMonths1.
     */
    public RowSet getLovMonths1() {
        return (RowSet) getAttributeInternal(LOVMONTHS1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovCountries1.
     */
    public RowSet getLovCountries1() {
        return (RowSet) getAttributeInternal(LOVCOUNTRIES1);
    }


}

