package model;

import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 03 09:21:19 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OpenItemsImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OpenItemsImpl() {
    }

    public void sortInMemory(){ 
           setQueryMode(ViewObject.QUERY_MODE_SCAN_VIEW_ROWS);
           setSortBy("selected");   // setOrderByClause("Table_Column_Name")
           executeQuery();
           System.out.println(getQuery());
           System.out.println(getWhereClause());
    }
}

