package model.common;

import java.math.BigDecimal;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 28 21:57:10 CST 2018
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    String getSequenceNextVal(String sequenceName);

    String getCollector(String custId);

    String getSalesPerson(String custId);

    void applyAgainstOldest(String custId, BigDecimal totalAmountTemp);
}

